export { default as HomePage } from './HomePage';
export { default as ProductPage } from './ProductPage';
export { default as ProductDetailPage } from './ProductDetailPage';
export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as NotFoundPage } from './NotFoundPage';
export { default as UsersPage } from './UsersPage';
export { default as CategoryPage } from './CategoryPage';
export { default as SearchResultsPage } from './SearchResultsPage';